# Naive Bayes for Data Discrete: Dữ liệu rời rạc

In [ ]:
import numpy as np
# Navie Bayes classification
class NB():
  def fit(self,X,y):
    self.X = X
    self.Label = y
    # Lấy ra các giá trị đơn trị của nhãn
    self.Label_unique = np.unique(y)
    # Tính xác suất cho từng nhãn
    self.P_Label = np.array([(self.Label[self.Label==value].size/self.Label.size ) for value in self.Label_unique])
  def predict(self,x_pred):
    P_result = np.array([np.prod(((self.X[self.Label == value])== x_pred).sum(axis=0)/(self.Label[self.Label == value]).size)  for value in self.Label_unique])*self.P_Label
    print(P_result)
    return self.Label_unique[np.argmax(P_result)] # Kết quả phân lớp lấy ra nhãn có xác suất là lớn nhất

In [ ]:
import pandas as pd

In [ ]:
FILE_PATH = '/content/drive/MyDrive/AIO 2024/Module_2/Week-3/CN/Book1.csv'

In [ ]:
df = pd.read_csv(FILE_PATH)
df

Outlook Temperature Humidity    Wind PlayTennis
0     Sunny         Hot     High    Weak         No
1     Sunny         Hot     High  Strong         No
2  Overcast         Hot     High    Weak        Yes
3      Rain        Mild     High    Weak        Yes
4      Rain        Cool   Normal    Weak        Yes
5      Rain        Cool   Normal  Strong         No
6  Overcast        Cool   Normal  Strong        Yes
7  Overcast        Mild     High    Weak         No
8     Sunny        Cool   Normal    Weak        Yes
9      Rain        Mild   Normal    Weak        Yes

In [ ]:
df = df.to_numpy()
df

array([['Sunny', 'Hot', 'High', 'Weak', 'No'],
       ['Sunny', 'Hot', 'High', 'Strong', 'No'],
       ['Overcast', 'Hot', 'High', 'Weak', 'Yes'],
       ['Rain', 'Mild', 'High', 'Weak', 'Yes'],
       ['Rain', 'Cool', 'Normal', 'Weak', 'Yes'],
       ['Rain', 'Cool', 'Normal', 'Strong', 'No'],
       ['Overcast', 'Cool', 'Normal', 'Strong', 'Yes'],
       ['Overcast', 'Mild', 'High', 'Weak', 'No'],
       ['Sunny', 'Cool', 'Normal', 'Weak', 'Yes'],
       ['Rain', 'Mild', 'Normal', 'Weak', 'Yes']], dtype=object)

In [ ]:
df[df[:,-1]=='Yes'][:,:-1]

array([['Overcast', 'Hot', 'High', 'Weak'],
       ['Rain', 'Mild', 'High', 'Weak'],
       ['Rain', 'Cool', 'Normal', 'Weak'],
       ['Overcast', 'Cool', 'Normal', 'Strong'],
       ['Sunny', 'Cool', 'Normal', 'Weak'],
       ['Rain', 'Mild', 'Normal', 'Weak']], dtype=object)

In [ ]:
df[df[:,-1]=='Yes'][:,:-1] == np.array(['Sunny','Cool','High','Strong'])

array([[False, False,  True, False],
       [False, False,  True, False],
       [False,  True, False, False],
       [False,  True, False,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
clf = NB()
clf.fit(df[:,:-1],df[:,-1])
clf.Label_unique

array(['No', 'Yes'], dtype=object)

In [ ]:
clf.predict(np.array(['Sunny','Cool','High','Strong']))

[0.01875    0.00277778]


'No'

In [ ]:
# Multi-Label classification
FILE_PATH2 = '/content/drive/MyDrive/AIO 2024/Module_2/Week-3/CN/MultiLabel.csv'

In [ ]:
df = pd.read_csv(FILE_PATH2)
df

Day  Season     Fog    Rain      Class
0    Weekday  Spring     NaN     NaN    On Time
1    Weekday  Winter     NaN  Slight    On Time
2    Weekday  Winter     NaN     NaN    On Time
3    Holiday  Winter    High  Slight       Late
4   Saturday  Summer  Normal     NaN    On Time
5    Weekday  Autumn  Normal     NaN  Very Late
6    Holiday  Summer    High  Slight    On Time
7     Sunday  Summer  Normal     NaN    On Time
8    Weekday  Winter    High   Heavy  Very Late
9    Weekday  Summer     NaN  Slight    On Time
10  Saturday  Spring    High   Heavy  Cancelled
11   Weekday  Summer    High  Slight    On Time
12   Weekday  Winter  Normal     NaN       Late
13   Weekday  Summer    High     NaN    On Time
14   Weekday  Winter  Normal   Heavy  Very Late
15  Saturday  Autumn    High  Slight    On Time
16   Weekday  Autumn     NaN   Heavy    On Time
17   Holiday  Spring  Normal  Slight    On Time
18   Weekday  Spring  Normal     NaN    On Time
19   Weekday  Spring  Normal   Heavy    On Time

In [ ]:
clf = NB()

In [ ]:
df = df.to_numpy()
df

array([['Weekday', 'Spring', nan, nan, 'On Time'],
       ['Weekday', 'Winter', nan, 'Slight', 'On Time'],
       ['Weekday', 'Winter', nan, nan, 'On Time'],
       ['Holiday', 'Winter', 'High', 'Slight', 'Late'],
       ['Saturday', 'Summer', 'Normal', nan, 'On Time'],
       ['Weekday', 'Autumn', 'Normal', nan, 'Very Late'],
       ['Holiday', 'Summer', 'High', 'Slight', 'On Time'],
       ['Sunday', 'Summer', 'Normal', nan, 'On Time'],
       ['Weekday', 'Winter', 'High', 'Heavy', 'Very Late'],
       ['Weekday', 'Summer', nan, 'Slight', 'On Time'],
       ['Saturday', 'Spring', 'High', 'Heavy', 'Cancelled'],
       ['Weekday', 'Summer', 'High', 'Slight', 'On Time'],
       ['Weekday', 'Winter', 'Normal', nan, 'Late'],
       ['Weekday', 'Summer', 'High', nan, 'On Time'],
       ['Weekday', 'Winter', 'Normal', 'Heavy', 'Very Late'],
       ['Saturday', 'Autumn', 'High', 'Slight', 'On Time'],
       ['Weekday', 'Autumn', nan, 'Heavy', 'On Time'],
       ['Holiday', 'Spring', 'Normal'

In [ ]:
# Huấn luyện mô hình
clf.fit(df[:,:-1],df[:,-1])

In [ ]:
clf.Label_unique

array(['Cancelled', 'Late', 'On Time', 'Very Late'], dtype=object)

In [ ]:
# Dự đoán mô hình
clf.predict(np.array(['Weekday','Winter','High','Heavy']))

[0.         0.         0.00262391 0.02222222]


'Very Late'

# Gaussian Naive Bayes for classification with Continuous Data: Dữ liệu liên tục

In [ ]:
class GaussianNB():
  def fit(self,X,y):
    self.X= X
    self.Label = y
    self.Label_unique = np.unique(self.Label)
    self.P_Label = np.array([self.Label[self.Label==value].size/self.Label.size for value in self.Label_unique])
  def predict(self,x_pred):
    # Tính mean cho từng feature khi Label = ... Xảy ra
    self.mean = np.array([self.X[self.Label==value].mean(axis=0) for value in self.Label_unique])
    # Tính variance(Phương sai bình phương) cho từng feature khi Label= ... xảy ra
    self.var = np.array([self.X[self.Label==value].var(axis=0) for value in self.Label_unique])

    self.P_result = np.prod((1/np.sqrt(2*np.pi*self.var))*np.exp((-(x_pred-self.mean)**2)/(2*self.var)),axis=1).flatten()*self.P_Label
    return self.Label_unique[np.argmax(self.P_result)]

In [ ]:
FILE_PATH3 = '/content/drive/MyDrive/AIO 2024/Module_2/Week-3/CN/iris.data.csv'

In [ ]:
df = pd.read_csv(FILE_PATH3)
df

1    2    3    4           Label
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df = df.to_numpy()
df

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [ ]:
Label = df[:,-1].astype(str)
print(f"Label: {Label}")
X_train = df[:,:-1].astype(float)
print(f"X_train: {X_train}")

Label: ['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-ver

In [ ]:
# Mã hóa Nhãn
Label_unique = np.unique(Label)
print(f"Label_unique: {Label_unique}")
for i in range(Label_unique.size):
  Label = np.char.replace(Label,Label_unique[i],str(i))
Label= Label.astype(float)

Label_unique: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [ ]:
print(Label)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2.]


In [ ]:
# Khởi tạo mô hình
clf = GaussianNB()

In [ ]:
# Huấn luyện mô hình
clf.fit(X_train,Label)

In [ ]:
# Dự đoán mô hình
clf.predict(np.array([4.9 ,3.1 ,1.5 ,0.1]))

np.float64(0.0)

In [ ]:
clf.P_result/np.sum(clf.P_result)

array([1.00000000e+00, 3.20343686e-18, 1.12989380e-25])